import { String, Array, Function, pipe } from 'effect'
pipe(
  [
    ' ',
    '163 ',
    ' depth                   ',
    '\n',
    ' 168 ',
    ' handle-drop             ',
    '\n',
    ' 165 ',
    ' height                  ',
    '\n',
    ' 204 ',
    ' primary-material        ',
    '\n',
    ' 167 ',
    ' shoulder-strap-drop     ',
    '\n',
    ' 197 ',
    ' shoulder-strap-drop-max ',
    '\n',
    ' 198 ',
    ' shoulder-strap-drop-min ',
    '\n',
    ' 170 ',
    ' shoulder-strap-length   ',
    '\n',
    ' 172 ',
    ' strap-length            ',
    '\n',
    ' 154 ',
    ' width         ',
  ],
  Array.map(String.trim),
  Array.chunksOf(3),
  Array.prepend(['key', 'value', 'description']),
  Array.map(Array.join(',')),
  Array.join('\n'),
  console.info,
)

console.log(Array.prepend.toString)
